name: 🐛 Bug report
description: Create a report to help us improve
labels: ["bug"]

body:
  # checkbox which asks the user if they have checked if the same type of issue has already been raised

  - type: checkboxes
    id: duplicate
    attributes:
      label: Have you checked if the same issue has already been raised ?
      options:
        - label: I have checked and didn't find similar issue
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false

  - type: textarea
    attributes:
      label: Desktop
      description: Please complete the following information
      value: |
        - OS: [e.g. iOS]
        - Browser: [e.g. chrome, safari]
        - Version: [e.g. 22]
    validations:
      required: false

  - type: textarea
    attributes:
      label: Smartphones
      description: Please complete the following information
      value: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false